image: mcr.microsoft.com/dotnet/sdk:6.0.100-preview.7

stages:
  - build
  - tests
  - nuget

build:
  stage: build
  only:
    - branches
  script:
    - dotnet build
  retry: 2

# tests:
#   stage: tests
#   only:
#     - branches
#   script:
#     - dotnet test --collect:"XPlat Code Coverage"
#   retry: 2

nuget:
  stage: nuget
  only:
    - branches
  script:
    - dotnet build
    - dotnet pack --include-symbols -p:PackageVersion=0.0.$CI_PIPELINE_ID
    - dotnet nuget push "**/*.symbols.nupkg" --source gitlab
  retry: 2
